import * as stylex from '@stylexjs/stylex'
import { ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html {...stylex.props(styles.reset)} lang="en">
      <body {...stylex.props(styles.reset)}>{children}</body>
    </html>
  )
}

const styles = stylex.create({
  reset: {
    minHeight: '100%',
    padding: 0,
    margin: 0,
  },
})
